defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  github.com/mikluko/jmap-mcp: gcr.io/distroless/static:nonroot

builds:
  - id: jmap-mcp
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Env.VERSION}}
