defaultBaseImage: cgr.dev/chainguard/static:latest
baseImageOverrides:
  github.com/mikluko/jmap-mcp: cgr.dev/chainguard/static:latest

builds:
  - id: jmap-mcp
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Env.VERSION}}
